server:
  port: 7002
eureka:
  instance:
    #eureka的服务端实例名称之前一台服务端时时localhost，现在是集群，要写如下
    hostname: eureka7002.com
  client:
    #    false表示不向注册中心注册自己
    register-with-eureka: false
    #    false表示自己端就是驻车中心，我的职责就是维护服务实例，并不需要检索服务
    fetch-registry: false
    service-url:
      #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址，集群需要相互注册相互访问，所以写7001的地址
      defaultZone: http://eureka7001.com:7001/eureka/